title: 초슬로그 🎯
author: chowisely
email: potress7@gmail.com
description: honesty integrity excellence # this means to ignore newlines until "show_exerpts:"
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  analytics_id: "G-SGMF6NV0B4"
  name: chowisely
  tagline: undergraduate in CS
  motto: honesty integrity excellence
  date_format: "%b %-d, %Y"
  #disqus_shortname: chowisely
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/profile1.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    github:  chowisely
    #twitter:
    #linkedIn:
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #email: jekyll

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

collections:
  blog:
    output: true
    permalink: /:collection/:name

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
#- jekyll-feed

paginate: 10
#paginate_path: "/blog/page:num"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

highlighter: rouge

#url: localhost:3002
url: https://chowisely.github.io
